name: 'ğŸ·ï¸ PR Labels'

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

jobs:
  scope-labels:
    name: Label the PR scope
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v5
        with:
          configuration-path: .github/pr-scope-labeler.yml
          sync-labels: true

  size-labels:
    runs-on: ubuntu-latest
    name: Label the PR size
    steps:
      - uses: codelytv/pr-size-labeler@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          xs_label: 'ğŸ¤© size/xs'
          xs_max_size: '10'
          s_label: 'ğŸ¥³ size/s'
          s_max_size: '100'
          m_label: 'ğŸ˜ size/m'
          m_max_size: '500'
          l_label: 'ğŸ˜– size/l'
          l_max_size: '1000'
          xl_label: 'ğŸ¤¯ size/xl'
          fail_if_xl: 'false'
          message_if_xl: >
            This PR exceeds the recommended size of 1000 lines.
            Please make sure you are NOT addressing multiple issues with one PR.
            Note this PR might be rejected due to its size.
          files_to_ignore: 'pnpm-lock.yaml *.lock docs/*'

  conventional-release-labels:
    runs-on: ubuntu-latest
    name: Conventional release labels
    steps:
      - uses: bcoe/conventional-release-labels@v1
        with:
          type_labels: '{"feat": "ğŸš€ Feature", "fix": "ğŸ•µğŸ» Fix", "breaking": "âš ï¸ Breaking Change"}'
